/**
 * Types for the HomeToClean data layer (src/data/*.json).
 *
 * Every page on the site is generated from these files. Nothing about the site
 * structure is hardcoded in a template, so adding a town or a service here is
 * the only edit needed to produce new pages.
 *
 * See README.md for how to extend the data.
 */

/** Publication batch. Controls what enters the sitemap. See README. */
export type Batch = 0 | 1 | 2 | 3;

/**
 * How confident we are in a published price range.
 * - `researched`: taken from published Singapore market sources, stated basis.
 * - `unknown`: no reliable market rate found. Render as "quoted on request",
 *   never as a number.
 */
export type PriceConfidence = 'researched' | 'unknown';

/** Basis on which a service is billed. Never conflate hourly with flat rate. */
export type PricingModel =
  | 'hourly'
  | 'flat_rate_by_property_size'
  | 'flat_rate_by_size_and_debris'
  | 'flat_rate_by_property_size_seasonal'
  | 'per_item';

export interface PriceRangeSGD {
  /** Lowest typical market price in SGD, before GST. `null` if not established. */
  min: number | null;
  /** Highest typical market price in SGD, before GST. `null` if not established. */
  max: number | null;
  /** Human-readable billing basis, e.g. "per hour", "per session, by property size". */
  unit: string;
  /** Caveats, per-size breakdown, GST position, seasonal effects. Rendered to users. */
  notes: string;
  confidence: PriceConfidence;
  /** Where the figures came from. Internal provenance; not rendered. */
  sourceBasis: string;
  /** Minimum billable hours a vendor typically enforces. `null` for flat-rate services. */
  minimumHours: number | null;
}

export interface Faq {
  q: string;
  a: string;
}

/** One step in how a service is actually carried out. */
export interface ProcessStep {
  title: string;
  body: string;
}

/** Pointer to a better-fitting service, with the reason a customer would switch. */
export interface ServiceAlternative {
  serviceSlug: ServiceSlug;
  reason: string;
}

export interface Service {
  slug: string;
  name: string;
  /** Contains the literal token `{town}`, substituted on location pages. */
  h1Template: string;
  /** H1 for the non-location service page. */
  h1Default: string;
  shortDescription: string;
  longDescription: string;
  pricingModel: PricingModel;
  priceRangeSGD: PriceRangeSGD;
  inclusions: string[];
  exclusions: string[];
  /** Keyed by PropertyType['slug']. */
  typicalDurationByProperty: Record<string, string>;
  chooseThisIf: string[];
  /** Drives the "is this the right service?" section. */
  chooseInsteadIf: ServiceAlternative[];
  faqs: Faq[];
  /** How the service runs, in order. Rendered as the process section. */
  process: ProcessStep[];
  relatedServiceSlugs: string[];
  /** Whether this service generates /cleaning/{service}/{town}/ pages. */
  locationEnabled: boolean;
  batch: Batch;
}

export interface Location {
  slug: string;
  name: string;
  /** Must reference other Location slugs. Validated by scripts/validate-data.mjs. */
  adjacentSlugs: string[];
  batch: Batch;
  /** Keyed by PropertyType['slug']. Drives per-town pricing tables. */
  dominantPropertyTypes: string[];
  /**
   * 60-100 words of genuinely town-specific fact: flat types and floor areas,
   * estate age, private stock, BTO handover activity. This is what stops every
   * location page being the same page with a swapped noun.
   */
  housingProfile: string;
  /** Internal operational note. Not rendered. */
  notes: string;
}

export type PropertyCategory = 'hdb' | 'condo' | 'landed';

export interface Range {
  min: number;
  max: number;
}

export interface PropertyType {
  slug: string;
  name: string;
  category: PropertyCategory;
  floorAreaSqm: Range;
  floorAreaSqft: Range;
  /** Hours for a routine (part-time) clean. */
  regularCleanHours: Range;
  /** Flat rate in SGD for a deep clean, before GST. `null` where site-visit-only. */
  deepCleanFlatRateSGD: Range | null;
  deepCleanHours: Range;
  batch: Batch;
  notes: string;
}

/** One /cleaning/{service}/{town}/ page. Generated by scripts/gen-combos.mjs. */
export interface Combo {
  serviceSlug: string;
  townSlug: string;
  batch: Batch;
  /** Master switch. `false` keeps the page out of the build and the sitemap. */
  published: boolean;
  /**
   * The paragraph that makes this page fail the swap test on purpose: why this
   * service specifically matters in this town, written against its housing
   * stock. `null` means not yet written.
   *
   * A combo cannot be published without one. That is enforced in
   * scripts/validate-data.mjs, so it is impossible to ship a thin location
   * page by flipping a flag.
   */
  localAngle: string | null;
}

export interface OperatingHours {
  days: string[];
  /** 24-hour "HH:MM". */
  opens: string;
  closes: string;
}

export interface Address {
  street: string;
  unit: string;
  postalCode: string;
  locality: string;
  /** ISO 3166-1 alpha-2. */
  country: string;
}

export interface FormSubmitConfig {
  /** FormSubmit AJAX endpoint. Swap the address for the hashed alias once activated. */
  endpoint: string;
  /** Subject line of the notification email. */
  subject: string;
  note: string;
}

export interface Company {
  /** Registered entity. Must appear in the footer. */
  entityName: string;
  tradingName: string;
  /** Placeholder `[UEN]` until supplied. */
  uen: string;
  yearEstablished: number;
  /** Absolute origin, no trailing slash. Used for canonicals and JSON-LD @id. */
  siteUrl: string;
  address: Address;
  /** Empty: this site is form-only, with no telephone channel. */
  phone: string;
  phoneDisplay: string;
  /** Empty: no WhatsApp channel. */
  whatsappNumber: string;
  email: string;
  operatingHours: OperatingHours[];
  operatingHoursDisplay: string;
  gstRatePercent: number;
  /** `null` until confirmed. Determines whether prices are shown "before GST". */
  gstRegistered: boolean | null;
  /** We match customers to vendors. We do not perform cleaning. */
  businessModel: 'matching';
  businessModelStatement: string;
  /** The enquiry form is the only contact channel. */
  contactModel: 'form-only';
  formSubmit: FormSubmitConfig;
}

// Slug unions are widened to `string` because the data files are the source of
// truth and are validated at build time rather than at type level. Narrowing
// these would mean editing types every time a town is added, which is exactly
// what the data-driven design is meant to avoid.
export type ServiceSlug = string;
export type LocationSlug = string;
export type PropertyTypeSlug = string;
